### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by RanajitRoy** [RanajitRoy/votingApp#16]
After login, the buttons "Cast Vote" and "Verify Vote" are sometimes not working as expected.
Sometimes it works after a time period.

**Comment by ArnabKBasu** [comment]
"Cast Vote" and "Verify Vote" Buttons are kept disabled until the voter data is fetched from the server. After the voter data is received, Button will function properly..

For Better understanding I have changed the color of the disabled buttons. Until the data is fetched, the button color will remain Gray and a Progress Bar will be visible. Once the data is received, Button will get activated and It will change color to Blue.
